export declare const sendSignupEmail: (to: string, firstName: string) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendLoginEmail: (to: string, firstName: string, ipAddress?: string) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendOtpEmail: (to: string, firstName: string, otp: string, expiresInMinutes?: number) => Promise<void>;
export declare const sendForgotPasswordEmail: (to: string, firstName: string, resetToken: string) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendResetPasswordSuccessEmail: (to: string, firstName: string) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendLogoutEmail: (to: string, firstName: string) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendDepositEmail: (to: string, firstName: string, amount: number, newBalance: number, ref?: string) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendWithdrawalEmail: (to: string, firstName: string, amount: number, newBalance: number, ref?: string) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendBudgetAddedEmail: (to: string, firstName: string, budgetName: string, limit: number) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendBudgetRemovedEmail: (to: string, firstName: string, budgetName: string) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendBudgetDepositEmail: (to: string, firstName: string, budgetName: string, amount: number, budgetBalance: number) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendBudgetWithdrawEmail: (to: string, firstName: string, budgetName: string, amount: number, mainBalance: number) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendGoalAddedEmail: (to: string, firstName: string, goalName: string, targetAmount: number, deadline?: string) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendGoalRemovedEmail: (to: string, firstName: string, goalName: string) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendGoalDepositEmail: (to: string, firstName: string, goalName: string, amount: number, savedSoFar: number, targetAmount: number) => Promise<import("resend").CreateEmailResponseSuccess>;
export declare const sendGoalWithdrawEmail: (to: string, firstName: string, goalName: string, amount: number, mainBalance: number) => Promise<import("resend").CreateEmailResponseSuccess>;
//# sourceMappingURL=emailService.d.ts.map